### ISSUE TITLE
Windows XP support

### ISSUE THREAD

**Issue by ardanew** [GiovanniDicanio/WinReg#12]
In windows XP there is no RegGetValue function
Maybe should use RegQueryValueEx instead?

or something like (not fully working in some cases)
`
	LONG RegGetValueXP(HKEY    hkey,
		LPCWSTR lpSubKey,
		LPCWSTR lpValue,
		DWORD   dwFlags,
		LPDWORD pdwType,
		PVOID   pvData,
		LPDWORD pcbData)
	{
		return RegQueryValueEx(hkey, lpValue, nullptr, pdwType, (LPBYTE)pvData, pcbData);
	}
`

**Comment by GiovanniDicanio** [comment]
I'm sorry, I currently have no plans to support Windows XP (I may consider doing that as a paid contract, though).

I think that using the WinXP-compatible RegQueryValueEx does have some security problems and requires more checks (and so writing more complex code).
For example, when retrieving string data, RegGetValue checks for a terminating NUL character, and if it is not found, the function _automatically_ adds one and returns a safe NUL-terminated string back to the caller. On the other hand, RegQueryValueEx is less safe in that regard, as it does _not_ perform such nice security check on strings read from the registry. So, we have to write additional code ourselves for that purpose. 
So, back-porting the current code to Windows XP is not just a matter of simply forwarding calls to RegQueryValueEx, but it would require a detailed code analysis, and likely writing additional code to keep good level of safety (e.g. regarding proper NUL-termination of strings retrieved from the registry).
