### ISSUE TITLE
Incredibly good library! NuGet Package?

### ISSUE THREAD

**Issue by VideoPlayerCode** [GiovanniDicanio/WinReg#14]
Thanks @GiovanniDicanio for an extremely well-written, light and easy to use library! Seriously great work!

I noticed that it's been "final" for a long time and barely changes, so maybe it's time to add it to Microsoft's NuGet (https://www.nuget.org/) so that it can be added as an auto-installed dependency in Visual Studio? Since it doesn't change often, it would be a very easy way for people to install the library.

What do you think?

**Comment by VideoPlayerCode** [comment]
@GiovanniDicanio I forgot to also say: Thanks for making the library wstring/Unicode-based and modern by default. It's great to see how much care and detail you have put into following proper, modern standards. Nobody should be making anything other than Unicode applications these days! ;-)

**Comment by WimLeflere** [comment]
Getting the library into [vcpkg](https://github.com/microsoft/vcpkg) might also be handy.

**Comment by GiovanniDicanio** [comment]
@VideoPlayerCode: Thanks for your compliments. I'm glad you like this library.

I'm not familiar with the package managers cited in this thread. Do you think they are really worth for a header-only easily reusable library like this?

**Comment by Loqaritm** [comment]
@GiovanniDicanio: Mostly relating to @WimLeflere's suggestion:

Getting (not really, but read on) the package to [vcpkg](https://github.com/microsoft/vcpkg) proved quite useful for the project I'm working on right now. The objective was to have all the needed libraries imported (and built) as  dependencies in one place and then exported as a nuget package. It lets them be easily updated outside of the main project and  keeps things tidy.

Now, the part I said I'd get back to: I've done it for a local mirror of vcpkg. Turns out writing the vcpkg portfiles for header-only libraries isn't much work at all. I'd be happy to share it, if You want to submit it there.

**Comment by GiovanniDicanio** [comment]
@Loqaritm: Thanks for your feedback and your enlightening comment. So, I think I'll investigate this vcpkg option, and I'll try to get it to vcpkg. If I have some questions, may I ask you for some guidance, as you seem to already have experience with it? Thanks.

**Comment by Loqaritm** [comment]
Not a problem! I don't have that much experience, but when I was writing it myself I've used mostly suggestions from here: https://vcpkg.readthedocs.io/en/latest/examples/packaging-github-repos/

I'd also suggest having a look at range-v3-vs2015 portfile.

I didn't mean to hijack the thread though, getting the package to NuGet would also be beneficial in its own right.

**Comment by VideoPlayerCode** [comment]
@Loqaritm

Hmm, seems like vcpkg exists as a nuget plugin:

https://github.com/bengreenier/vcpkg.nuget/blob/master/README.md

This plugin seems ro allow visual studio to interact with vcpkg projects.

So that would work too...

Visual Studio set to nuget-install this vcpkg plugin, and then that plugin set to install vcpkg libraries.

If I understood it correctly, it means that it would be fine to only distribute as a vcpkg.

I am actually very unfamiliar with vcpkg... Is it possible to make a package by just adding some files to a github repo? Or do all packages have to be added to the official vcpkg repo? Here’s something which mentions ”package from github”: https://vcpkg.readthedocs.io/en/latest/examples/packaging-github-repos/

@GiovanniDicanio

The purpose for having the library on a package distribution site is that it allows open source projects to link to your library instead of bundling a copy in the source tree.

So for example with NuGet, any user who opens an open source .sln file that links to your project, would auto-download your library.

**Comment by Loqaritm** [comment]
@VideoPlayerCode 
The project You've linked seems interesting, though I worry it's a little bit obscure. But I may be misunderstanding it.

I think that vcpkg and NuGet should be treated separately, that's why I was apologising for hijacking the thread. Vcpkg provides an easy way to download and install packages (I've been thinking about it as a sort of 'apt-get' for windows (though that comparison might be a little far-fetched)), I've found it most useful in bigger projects where downloading all the needed packages is just a part of a pipeline for creating dependencies.

On the other hand, NuGet provides an easy way to include a binary (well, in this case just the header) in any sort of project, and I think that providing it would certainly be a benefit in of itself.

As to how the packages are added to vcpkg - from my knowledge all the packages have to be added to official vcpkg repo. It's just about adding a portfile to vcpkg which points at this github repo.

**Comment by GiovanniDicanio** [comment]
I have very limited free time available for this side project right now, and I can't spend much time studying these package managers. So, if you guys who already have had some experience with these package managers would post here the text files that "describe" this header-only library for vcpkg and NuGet, we can work on them here, and I can upload them to the proper web sites. Of course, I will add proper credit to you in the README.

**Comment by Loqaritm** [comment]
Hey, I've also been quite busy lately, so that's why I'm answering so late.

Sure, no problem, I'll post vcpkg portfiles here (probably) on Monday

**Comment by VideoPlayerCode** [comment]
@GiovanniDicanio Yeah I understand. I have limited energy due to chronic illness, so I don't have energy for studying it either. But I did realize this much: vcpkg is a much better package manager than NuGet because it's available for every OS and isn't tied into Visual Studio. And vcpkg would be very easy. It is basically two textfiles submitted to the vcpkg repo.

https://vcpkg.readthedocs.io/en/latest/examples/packaging-github-repos/

That page suggests looking at `ports\range-v3` for a header-only library. So I went there:

https://github.com/microsoft/vcpkg/tree/master/ports/range-v3

So there's a file named `CONTROL` with general "package version/description" metadata, and then there is a file named `portfile.cmake` with instructions for how to install and compile the library:

https://github.com/microsoft/vcpkg/blob/master/ports/range-v3/portfile.cmake

In it, you specify `vcpkg_from_github()` with the repo name and commit/tag name (for which version of this library to import). That format is described in detail in the first link in my post here.

Next there is a `vcpkg_configure_cmake()` section which seems generic and is the same in another header-only library I looked at.

The rest of the file is a bunch of instructions to tell cmake to [compile the header](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_install_cmake.md), and how to copy/rename various files from the cloned repo to the final imported project dir (such as copying LICENSE.txt and then renaming it to copyright).

Overall the format seems easy, but this is as far as my energy is able to research this...

**Comment by GiovanniDicanio** [comment]
No problem, everyone. We all have paying projects, and a life. I think I'll focus on **vcpkg**. Yes, I read there are some text files to describe the package, but I need some time to figure out the details.

**Comment by GiovanniDicanio** [comment]
OK, so the `CONTROL` file could look like this:

```
Source: winreg-vs2015
Version: 1.2.1
Homepage: https://github.com/GiovanniDicanio/WinReg
Description: High-level C++ wrapper around the Windows Registry C API.
```
And the `portfile.cmake` like this:

```
include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO GiovanniDicanio/WinReg
    REF v1.2.1
    SHA512 1 // TODO FIX 
    HEAD_REF master
)

file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/winreg-vs2015 RENAME copyright)
file(INSTALL ${SOURCE_PATH}/WinReg/WinReg/WinReg.hpp DESTINATION ${CURRENT_PACKAGES_DIR} )
```

Now, I need to figure out the SHA512.

**Comment by Loqaritm** [comment]
@GiovanniDicanio 
That's actually pretty much exactly what I wanted to post! :)
As for SHA512:
1. Leave it as 1.
2. Clone and configure vcpkg:
```
> git clone https://github.com/Microsoft/vcpkg.git
> cd vcpkg

PS> .\bootstrap-vcpkg.bat
Linux:~/$ ./bootstrap-vcpkg.sh
```
3. Create a folder for WinReg in `ports` folder
4. Put the `CONTROL` and `portfile.cmake` in this folder
5. Run `./vcpkg install winreg-vs2015`
6. This will shout at you for not providing the correct SHA512 - and in all the yelling it's going to tell You the correct one. Just copy and paste it into the portfile then.

**Comment by GiovanniDicanio** [comment]
When I run `vcpkg install winreg-vs2015`, I get the following output, ending with an error message:

```
The following packages will be built and installed:
    winreg-vs2015[core]:x86-windows
Starting package 1/1: winreg-vs2015:x86-windows
Building package winreg-vs2015[core]:x86-windows...
Running vswhere.exe failed with message:
Visual Studio Locator version 1.0.62
Copyright (C) Microsoft Corporation. All rights reserved.

Error 0x57: Unknown parameter: prerelease
```

There seems to be a problem with a tool called vswhere.exe.

**Comment by GiovanniDicanio** [comment]
After going through all the hoops to get the SHA512 (including updating the `vswhere.exe` that came with VS2015 Update 3), I got the following error:

`The folder /include is empty or not present. This indicates the library was not correctly installed.
`

So, it seems vcpkg wants me to modify the project structure adding an `/include` folder, and putting the `WinReg.hpp` file under there.

For the record, this is the current `CONTROL` file:

```
Source: winreg-vs2015
Version: 1.2.1
Homepage: https://github.com/GiovanniDicanio/WinReg
Description: High-level C++ wrapper around the Windows Registry C API.
```

And this is the `portfile.cmake`:

```
include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO GiovanniDicanio/WinReg
    REF v1.2.1
    SHA512 c919f91bf37b2fd7c30f6463430e07f3b8d1a01b8d4c84591b56299faf9d5b651d7c3b35a2adc22e3b0aa471627060a45e179f98f309242683b17d4d0d81cb7b 
    HEAD_REF master
)

file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/winreg-vs2015 RENAME copyright)
file(INSTALL ${SOURCE_PATH}/WinReg/WinReg/WinReg.hpp DESTINATION ${CURRENT_PACKAGES_DIR} )
```

So far, at least for me, just downloading the single `WinReg.hpp` header and put it _wherever_ a project needs it (not necessarily under a hypothetical `include` sub-directory) would be much simpler :)

**Comment by VideoPlayerCode** [comment]
@GiovanniDicanio It looks like this line needs to be modified to make it install in the include folder:

`file(INSTALL ${SOURCE_PATH}/WinReg/WinReg/WinReg.hpp DESTINATION ${CURRENT_PACKAGES_DIR} )`

I am looking at these example portfiles:

https://github.com/microsoft/vcpkg/blob/master/ports/range-v3/portfile.cmake
https://github.com/microsoft/vcpkg/blob/master/ports/rapidjson/portfile.cmake
https://github.com/microsoft/vcpkg/blob/master/ports/boost-modular-build-helper/portfile.cmake

It seems like they always use the format `${CURRENT_PACKAGES_DIR}/share/boost-build` where `boost-build` is the name of a library, so you would probably use winreg-vs2015 (btw, why the vs2015 suffix? seems like portfile name should match the project name, in this case winreg).

---

Oh... while I was writing this comment I searched for "vcpkg hpp" and bingo!

https://github.com/microsoft/vcpkg/tree/master/ports/vulkan-hpp

`CONTROL`:

```
Source: vulkan-hpp
Version: 2019-05-11
Description: Header only C++ bindings for the Vulkan C API
Build-Depends: vulkan
```

`portfile.cmake`:

```python
# header-only library

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO KhronosGroup/Vulkan-Hpp
    REF 5ce8ae7fd0d9c0543d02f33cfa8a66e6a43e2150
    SHA512 dc58332f5075f0b4d001abd4e78664be099509b8cee525a211aa33599f2351bf5e200fef37dccc84895d8f7a056f075ae3cf404f9aac7281970ff903e4a67a96
    HEAD_REF master
)

file(COPY ${SOURCE_PATH}/vulkan/vulkan.hpp DESTINATION ${CURRENT_PACKAGES_DIR}/include/vulkan)

# Handle copyright
configure_file(${SOURCE_PATH}/LICENSE.txt ${CURRENT_PACKAGES_DIR}/share/${PORT}/copyright COPYONLY)
```

This teaches us a few things:

`${PORT}` is the name of the port, in this case `vulkan-hpp`, so it can be useful. It also confirms that `${CURRENT_PACKAGES_DIR}` isn't the folder we should be copying stuff to; it's the base-dir of where all packages are installed so we need to put ours in a subdir of that. And lastly, it shows that every port has some "share" subdir where they should place copyright-files.

I also researched why they use `configure_file` on the last line and see that it was a mistake by them: https://cmake.org/cmake/help/latest/command/configure_file.html (copies the file AND substitutes variables in the text, hehe). So _we_ won't be using that command.

---

So, try this as your new `CONTROL`:

```
Source: winreg
Version: 1.2.1
Homepage: https://github.com/GiovanniDicanio/WinReg
Description: High-level C++ wrapper around the Windows Registry C API.
```

And `portfile.cmake`:

```python
# header-only library

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO GiovanniDicanio/WinReg
    REF v1.2.1
    SHA512 c919f91bf37b2fd7c30f6463430e07f3b8d1a01b8d4c84591b56299faf9d5b651d7c3b35a2adc22e3b0aa471627060a45e179f98f309242683b17d4d0d81cb7b
    HEAD_REF master
)

file(COPY ${SOURCE_PATH}/WinReg/WinReg/WinReg.hpp DESTINATION ${CURRENT_PACKAGES_DIR}/include/${PORT})

# Handle copyright
file(COPY ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT}/copyright)
```

Let's see if this works!

**Comment by GiovanniDicanio** [comment]
Thanks both @Loqaritm  and @VideoPlayerCode!

Now it seems to work.

`CONTROL` file:

```
Source: winreg
Version: 1.2.1
Homepage: https://github.com/GiovanniDicanio/WinReg
Description: High-level C++ wrapper around the Windows Registry C API.
```

`portfile.cmake` file:

```
# WinReg - Header-only library

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO GiovanniDicanio/WinReg
    REF v1.2.1
    SHA512 c919f91bf37b2fd7c30f6463430e07f3b8d1a01b8d4c84591b56299faf9d5b651d7c3b35a2adc22e3b0aa471627060a45e179f98f309242683b17d4d0d81cb7b 
    HEAD_REF master
)

# Copy the single reusable library header
file(COPY ${SOURCE_PATH}/WinReg/WinReg/WinReg.hpp DESTINATION ${CURRENT_PACKAGES_DIR}/include/${PORT})

# Handle copyright
file(COPY ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT}/copyright)
```

**Comment by GiovanniDicanio** [comment]
So, I opened [this new issue](https://github.com/microsoft/vcpkg/issues/8179) on Microsoft's vcpkg repository, to ask about adding WinReg.

**Comment by VideoPlayerCode** [comment]
Fantastic! Looking forward to the results. :-) And this gives me a reason to learn vcpkg. Had been using NuGet to fetch a few big libraries but vcpkg is cross-platform and open, so it’s clearly way better. ;-)

**Comment by GiovanniDicanio** [comment]
It seems they opened a [pull request to add WinReg to vcpkg](https://github.com/microsoft/vcpkg/pull/8190).
So, I'm closing this issue here.

**Comment by VideoPlayerCode** [comment]
Sweet, congrats on getting it merged into vcpkg! :-) If you have time and energy, it would be nice if you mention that sweet install method in the https://github.com/GiovanniDicanio/WinReg/blob/master/README.md

Take care! :-)

**Comment by GiovanniDicanio** [comment]
Thank you very much @VideoPlayerCode! I added a note on vcpkg in the README, as per your suggestion.
