### ISSUE TITLE
Allow to build dll

### ISSUE THREAD

**Issue by egorpugin** [GiovanniDicanio/WinReg#20]
Hi,

Thank you for your work on non-throwing versions of functions!
I'll try it later today.

Next feature I'd like to ask is to add dll support.
Usually I do it by adding MY_LIB_API to class and function headers.
Example:
```
class WINREG_API RegKey { ... };

WINREG_API
void somefunc();
```

If you don't want to make big changes to VS SLN, it is possible to simply add empty definition in it `WINREG_API=`.
I use other build system anyway, but I can use those api specs to turn library into dll.

(I'm able to send a PR, but I don't want to touch any VS files myself.)

**Comment by egorpugin** [comment]
Also I'd like to ask if it is possible to use stable git tag version scheme? 3 or 2 numbers constantly.
We have `v1.2.1` and now `v2.0`.
This breaks some scripting and automation.

**Comment by GiovanniDicanio** [comment]
Hi, I modified the version scheme to use 3 numbers, following the first stable release.

Sorry, but I'm not sure what you are exactly asking about the DLL request. I usually export pure C functions from DLLs, because C++ classes and STL templates at the DLL boundaries can be problematic. I usually have something like preprocessor `MY_LIB_API` which expands to `__declspec(dllimport)` or `__declspec(dllexport)` based on the context (using the DLL from external code, or building the DLL, respectively). Thanks.

**Comment by egorpugin** [comment]
> I modified the version scheme to use 3 numbers, following the first stable release.

Ok, thank you.

> I usually have something like preprocessor MY_LIB_API which expands to __declspec(dllimport) or __declspec(dllexport)

Yes, exactly this. Is it possible to add it to classes/free functions?

> because C++ classes and STL templates at the DLL boundaries can be problematic

Yes, but having same compiler/runtime/etc. is ok with that (my case).

**Comment by GiovanniDicanio** [comment]
Yes, I know that it works you use the _same_ compiler C++ version, and the same switches, and the same flavor of the CRT, etc., but it's _very_ constraining.

Anyway, are you asking something like adding these lines in the WinReg.hpp header file?

```
#ifndef WINREG_API
#define WINREG_API
#endif
```

Then add the `WINREG_API` in all the class declarations in the header file? E.g.:

```
class WINREG_API RegKey 
{
  // Leave current code as is...
};
```

And do the same for `RegResult` and `RegException`?

And then you can `#define WINREG_API` as `__declspec(dllexport)` or `__declspec(dllimport)` in your custom build system based on the actual usage? (And the default is still that `WINREG_API` expands to nothing.)

**Comment by egorpugin** [comment]
Yes!

> And do the same for RegResult and RegException?

Did not check complete list of classes, but this is needed for everything public.

**Comment by egorpugin** [comment]
Not openings tons of tickets...

1)
I'm converting my code into TryFunctions.
What about adding RegResult method returning string error?
LONG code is fine, but I think it is a common operation to get string message directly without using FormatMessage everytime myself.

2)
Not a big one, but... both cpp and hpp files are full of spaces left on lines.
I use Trailing Whitespace Visualizer VS extension which clears those spaces on save.
![image](https://user-images.githubusercontent.com/4325333/79269747-9869de00-7ea5-11ea-9b85-ddaf68c3de8a.png)

**Comment by GiovanniDicanio** [comment]
I like this feedback, and improved the code accordingly. Thanks.

**Comment by egorpugin** [comment]
Thank you!

FYI here's my winreg build config (in C++!) https://software-network.org/org.sw.demo.giovannidicanio.winreg/2.1.0/specification

I develop SW - C++ build system and package manager.
