### ISSUE TITLE
Change "namespace detail" to "namespace winreg::detail"?

### ISSUE THREAD

**Issue by Akarinnnnn** [GiovanniDicanio/WinReg#34]
https://github.com/GiovanniDicanio/WinReg/blob/909856652e42ea51d12d97789759f14cb8fa75a3/WinReg/WinReg.hpp#L432

**Comment by GiovanniDicanio** [comment]
@Akarinnnnn I think `detail` is a _nested_ namespace, living under `winreg`. Or am I missing something? Thanks.

**Comment by Akarinnnnn** [comment]
> @Akarinnnnn I think `detail` is a _nested_ namespace, living under `winreg`:
> 
> https://github.com/GiovanniDicanio/WinReg/blob/909856652e42ea51d12d97789759f14cb8fa75a3/WinReg/WinReg.hpp#L73
> 
> So, it's already `winreg::detail`. Or am I missing something? Thanks.

Seemed like missing something making it outside the winreg namespace, I think.

**Comment by Akarinnnnn** [comment]
Seemed I was misleaded. Sorry
