### ISSUE TITLE
Default to 64-bit registry for 32-bit applications on 64-bit OS

### ISSUE THREAD

**Issue by Gfyss** [GiovanniDicanio/WinReg#37]
Situation: 32-bit program needs to read registry keys on 32 and 64-bit computers.  In this case I need the subkeys in:
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\Packages

The problem is that attempts to open that key on a 64-bit computer resulted in "Access Denied".  If I have the program list the subkeys of "Component Based Service" it doesn't list "Packages", but using a "reg query" does show that subkey.  It turns out the 32-bit program was being fed the keys stored in the HKLM\SOFTWARE\WOW6432Node\Microsoft\Windows\... path. 

Solution/workaround: The solution was to add "KEY_WOW64_64KEY" to the desired access request like this (KEY_READ | KEY_WOW64_64KEY).  I confirmed that this doesn't affect the results when run on a 32-bit OS.  I open a key with:
RegKey key{};
key.Open(HKEY_LOCAL_MACHINE, testSubKey, (REGSAM)(KEY_READ | KEY_WOW64_64KEY));

Proposal: Would it make sense to have the WinReg library default to using the KEY_WOW64_64KEY in access requests, or at least mention in the documentation that the default registry view depends on how you compile the program, especially a 32-bit app on a 64-bit OS?  

The Microsoft reference is here:
https://docs.microsoft.com/en-us/windows/win32/winprog64/accessing-an-alternate-registry-view

Thoughts?

**Comment by GiovanniDicanio** [comment]
Thanks for opening this issue. Before doing modifications to the current library behavior, I'd like to gather feedback from other library users.

**Comment by GiovanniDicanio** [comment]
Maybe as a first step I could modify the places where `KEY_READ | KEY_WRITE` are used as default argument, including also the `KEY_WOW64_64KEY` flag?
E.g.:

```
    // Wrapper around RegOpenKeyEx
    void Open(
        HKEY hKeyParent,
        const std::wstring& subKey,
        // Current code:
        // REGSAM desiredAccess = KEY_READ | KEY_WRITE
        //
        // Change to include also KEY_WOW64_64KEY:
        //
        REGSAM desiredAccess = KEY_READ | KEY_WRITE | KEY_WOW64_64KEY
    );

```

**Comment by GiovanniDicanio** [comment]
I chose to add that flag as default.
