### ISSUE TITLE
TryGetMultiStringValue only returns the first value

### ISSUE THREAD

**Issue by tluchowski** [GiovanniDicanio/WinReg#39]
Hello,

When I use TryGetMultiStringValue to obtain a REG_MULTI_SZ value, it only returns the first value.

I am reading a key that's populated in some cases when applications request a reboot: SYSTEM\CurrentControlSet\Control\Session Manager, property PendingFileRenameOperations

For instance, how the value in my registry is:
\??\C:\Windows\System32\Intel\HwKws\SET2048.tmp

\??\C:\Windows\System32\cAVS\Communication DLLs\SET257D.tmp

\??\C:\Windows\system32\drivers\SET49C5.tmp

However, TryGetMultiStringValue only returns the first value. I checked in the debugger that we only enter this loop once in function TryGetMultiStringValue:

while (*currStringPtr != L'\0')
    {
        // Current string is NUL-terminated, so get its length calling wcslen
        const size_t currStringLength = wcslen(currStringPtr);

        // Add current string to the result vector
        result.emplace_back(currStringPtr, currStringLength);

        // Move to the next string
        currStringPtr += currStringLength + 1;
    }

**Comment by tluchowski** [comment]
It looks a bit odd:
![image](https://user-images.githubusercontent.com/5471909/111704678-d99a0900-883f-11eb-8bfe-533392f08d22.png)

Please note empty lines, which are not visible for other properties:
![image](https://user-images.githubusercontent.com/5471909/111704721-e7e82500-883f-11eb-8460-776c45dd0de2.png)

**Comment by GiovanniDicanio** [comment]
I think this is a bug in the way the strings are stored in the registry, not in my code.

In fact, it seems that in the case you cited _empty_ strings are stored as part of the string sequence, and that is wrong.

From the [official MSDN documentation](https://docs.microsoft.com/en-us/windows/win32/sysinfo/registry-value-types):

> A REG_MULTI_SZ string ends with a string of length 0. Therefore, it is not possible to include a zero-length string in the sequence. An empty sequence would be defined as follows: \0.

**Comment by tluchowski** [comment]
Dear Giovanni,

Both you and I are correct - Microsoft states an empty line with \0 is not allowed, but they violate it :)

From https://bugs.python.org/issue32587: (it doesn't matter that it's regarding Python, it's a universal issue:)
MSDN documents that REG_MULTI_SZ is not supposed to have \0\0 anywhere else than in the end. The comment in  
https://github.com/python/cpython/blob/a5293b4ff2c1b5446947b4986f98ecf5d52432d4/PC/winreg.c#L504
clearly shows that Python has the assumption that this specification is actually correct. However, Microsoft is violating it eg in https://technet.microsoft.com/en-us/library/cc960241.aspx 

Some more docs on the very key, explaining the actual format of the data (one line with data, another line with data, or an empty line meaning "delete above":
https://forensicatorj.wordpress.com/2014/06/25/interpreting-the-pendingfilerenameoperations-registry-key-for-forensics/

**Comment by GiovanniDicanio** [comment]
It seems you are right: Microsoft in this specific registry key is violating its own rules :)

So, what should we here? Do you think the code for handling REG_MULTI_SZ should be modified to consider empty strings in the string list? So, even in the normal case of conforming REG_MULTI_SZ, should an empty wstring be returned back to the caller (representing the last \0)?

E.g.:

```
Connie\0
C64\0
Amiga\0
\0
```

Returns: `"Connie", "C64", "Amiga", ""`?

And for REG_MULTI_SZ with embedded null strings (like the PendingFileRenameOperations):
```
Connie\0
\0
C64\0
\0
```

Return: `"Connie", "", "C64", ""`

P.S.: Note that, according to [one](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-2000-server/cc960241(v=technet.10)?redirectedfrom=MSDN) of the links you posted about the PendingFileRenameOperations, it seems for Windows **internal use only**:

> This entry is maintained by Windows 2000 for internal use only. Do not change the value of this entry.

So, should I modify this library code only for this non-conforming registry key?
Are there similar cases of Microsoft violating its own rules about double-null-terminated strings in the registry?

**Comment by GiovanniDicanio** [comment]
Another option could be adding methods like TryGetMultiStringValueNC (NC = Non Conformant) to handle this specific case...
Or pass a flag to specify the desired behavior, and default to the proper conformant case.

**Comment by GiovanniDicanio** [comment]
I modified the existing methods to support also empty strings inside double-null-terminated strings. Thanks.

**Comment by tluchowski** [comment]
Thank you Giovanni!

Apologies I didnt reply to your previous emails, I was preoccupied with some family matters.

Kind regards
Tomasz

-------- Original message --------
From: GiovanniDicanio ***@***.***>
Date: 24/03/2021 18:54 (GMT+01:00)
To: GiovanniDicanio/WinReg ***@***.***>
Cc: Tomasz Luchowski ***@***.***>, Author ***@***.***>
Subject: Re: [GiovanniDicanio/WinReg] TryGetMultiStringValue only returns the first value (#39)


I modified the existing methods to support also empty strings inside double-null-terminated strings. Thanks.

**Comment by GiovanniDicanio** [comment]
No problem! Thank you for your feedback, and best wishes for your family.
