### ISSUE TITLE
Access denied with default RegKey constructor

### ISSUE THREAD

**Issue by WimLeflere** [GiovanniDicanio/WinReg#4]
The default RegKey constructor tries to open the registry key with read and write access.
https://github.com/GiovanniDicanio/WinReg/blob/b5dbf0ca1b17e9608f16a623384f9fbd4db4eca9/WinReg/WinReg/WinReg.hpp#L172

This cause problems for a lot of registry keys as they require elevated permissions to be able to be written.
E.g. 'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Enum\USB'

Maybe better to open the keys with read access only?
Or add the permission level as constructor argument?

**Comment by GiovanniDicanio** [comment]
I like the idea of adding a permission level as constructor argument.

**Comment by GiovanniDicanio** [comment]
I've updated the code with this addition. Thanks.
