### ISSUE TITLE
Need function TryQueryValueType

### ISSUE THREAD

**Issue by AndyWatterman** [GiovanniDicanio/WinReg#47]
Thank you for your very nice library.

I think it also need function "TryQueryValueType", because "QueryValueType" failing when value not set (see image):

![image](https://user-images.githubusercontent.com/61488512/155329284-81099d0d-d42b-466f-977c-fe9da1c218eb.png)

**Comment by sszth** [comment]
(value not set) is not a real value. It's just what you see in regedit when the (Default) value for the key is actually not set.
https://stackoverflow.com/questions/1832837/how-to-search-a-default-registry-entry-with-value-value-not-set-from-wix

**Comment by GiovanniDicanio** [comment]
@AndyWatterman Thanks for taking the time to open the issue, and for your compliment to the library. I'll take a look.

**Comment by GiovanniDicanio** [comment]
Fixed by #48 .
