### ISSUE TITLE
Visual Studio 2013 not supported

### ISSUE THREAD

**Issue by WimLeflere** [GiovanniDicanio/WinReg#6]
'noexcept' and 'constexpr' are not supported by Visual Studio 2013.
It would be nice if the code was updated so it could be used in a Visual Studio 2013 project.

**Comment by GiovanniDicanio** [comment]
I tend to use VS2015 these days for my C++ projects. I have no interest in supporting VS2013 for this library, so I prefer the use of more modern `noexcept` and `constexpr`. Of course, if you need to compile with older versions of VC++, feel free to substitute these keywords with the non-standard VC++ `throw()`, and `static const`, respectively.
