### ISSUE TITLE
open HKEY_LOCAL_MACHINE\SOFTWARE fail

### ISSUE THREAD

**Issue by SnowMeteors** [GiovanniDicanio/WinReg#65]
``` c++
#include <iostream>
#include <Windows.h>
#include <string>
#include "WinReg.hpp"

int main()
{
	winreg::RegKey  key{ HKEY_LOCAL_MACHINE, L"SOFTWARE" };

	return 0;
}
```
![image](https://github.com/GiovanniDicanio/WinReg/assets/47601098/341fab68-8970-41b9-85ba-e95f1138b2b5)
Is there any problem with my code and why is it throwing an exception
![image](https://github.com/GiovanniDicanio/WinReg/assets/47601098/7e9b2d21-5552-4e34-9f95-7e045df8a405)
The registry also exists

**Comment by GiovanniDicanio** [comment]
When you invoke that `RegKey` constructor, the [default desired access used](https://github.com/GiovanniDicanio/WinReg/blob/39f1a6193abcee4c8d14277a49532b0fcf6f9cdc/WinReg/WinReg.hpp#L130) is `KEY_READ|KEY_WRITE|KEY_WOW64_64KEY`.
The `RegCreateKeyExW` API fails with error code **5**, which is **ERROR_ACCESS_DENIED**.
So, do you have enough privileges to access that registry key?
You may want to try running that code as Administrator.
