### ISSUE TITLE
Build failure with mingw 32-bit

### ISSUE THREAD

**Issue by star-hengxing** [GiovanniDicanio/WinReg#73]
```
include/WinReg/WinReg.hpp: In function 'bool winreg::details::SizeToDwordCastIsSafe(size_t)':
include/WinReg/WinReg.hpp:932:5: error: assignment of read-only location 'size'
  932 |     UNREFERENCED_PARAMETER(size);
      |     ^~~~~~~~~~~~~~~~~~~~~~
```

```c
#define UNREFERENCED_PARAMETER (x) = (x)
```

I think we can use https://en.cppreference.com/w/cpp/language/attributes/maybe_unused

**Comment by GiovanniDicanio** [comment]
In VS 2019, the definition I found for the `UNREFERENCED_PARAMETER` macro is (from winnt.h):

`#define UNREFERENCED_PARAMETER(P)          (P)`

and the code compiles cleanly at /W4 with MSVC++.

I also tried using `[[maybe_unused]]`:

`[[nodiscard]] inline bool SizeToDwordCastIsSafe([[maybe_unused]] const size_t size) noexcept`

and the code compiles cleanly at /W4 as well.

I'm curious if you could pick a more correct definition of the `UNREFERENCED_PARAMETER` macro in your toolchain, that would compile cleanly.

**Comment by star-hengxing** [comment]
I am the maintainer of xmake-repo package management and this error come from ci auto update https://github.com/xmake-io/xmake-repo/pull/5637

This macro come from
https://github.com/mingw-w64/mingw-w64/blame/afd6e88a63ec3a8a2398836fe5762fd2afb06fc5/mingw-w64-headers/include/ntdef.h#L284

Your library uses the C++17 standard, so `[[maybe_unused]]` is recommended.

**Comment by GiovanniDicanio** [comment]
`UNREFERENCED_PARAMETER` is _not_ exactly the same as `[[maybe_unused]]`. Anyway, I modified the code using `[[maybe_unused]]` instead, to make your build process with MinGW 32-bit complete successfully.
